### PR TITLE
Conditional Revise support using `@requires`

### PR DESCRIPTION
**Pull request by jondeuce**
Following up on my comment https://github.com/Roger-luo/FromFile.jl/issues/30#issuecomment-1042478489, this PR enables Revise.jl to track files included via `@from`.

In order not to unconditionally depend on Revise (which was mentioned to be undesirable in a previous PR https://github.com/Roger-luo/FromFile.jl/pull/31#issuecomment-921981922, and I agree), this is done using the `@requires` mechanism from Requires.jl. This means that at the cost of a very lightweight dependency, there will be no effect on code using FromFile which does not have Revise loaded. This does mean that Revise needs to be loaded before FromFile in order for this method to work, but this is a very common workflow for Revise users: `using Revise` should be run before loading any code which should be tracked (see e.g. [the Revise docs](https://timholy.github.io/Revise.jl/stable/#Usage-example-1)).

The implementation is very simple: if Revise is available in an interactive session, call `Revise.track(mod, path)` on the dummy module `mod` generated by FromFile which wraps the `include(path)` statement.

Right now, the only logic which I'm not 100% sure about is whether or not Revise should track _every_ file included via `@from`, and whether it should only track changes in interactive sessions. I think the answer to both of these questions is yes: if a user has loaded Revise in an interactive session, I would think that they would prefer all possible code changes to be tracked. But still, an ability to opt out would be reasonable (environment variable?).

### CODE REVIEW

**Comment by Roger-luo** [comment]
Yes, Revise should track every file imported via `@from` since this macro should be similar to `include` or `includet`. 

Opt-out this is not necessary I think, I can't think of any use case for that, we can add opt-out options if someone actually reports a use case. So basically we need some tests then the rest should be good to go.

**Comment by jondeuce** [comment]
Alright, I've added some basic Revise tests which are passing nicely.

Unfortunately, when adding Revise as a dependency to the test project environment `test/Project.toml` I ran into a bug/error (https://github.com/JuliaLang/Pkg.jl/issues/1585) which I really cannot figure out. As far as I can tell it's still an outstanding issue, and `test` project environments are still somewhat in beta; see e.g. https://github.com/JuliaLang/Pkg.jl/issues/1585#issuecomment-616786874 and this [note](https://pkgdocs.julialang.org/v1/creating-packages/#Test-specific-dependencies-in-Julia-1.2-and-above) in the Pkg documentation.

As a workaround, I changed back to the old method of specifying test-specific dependencies in `Project.toml` via the [extras] and [targets] fields (https://pkgdocs.julialang.org/v1/creating-packages/#Test-specific-dependencies-in-Julia-1.0-and-1.1).

Sorry for the messy PR!

**Comment by Roger-luo** [comment]
have you tried `TestEnv.jl`? That should allow you to work around this issue. the test env is very hard to use indeed, but I think hacking `LOAD_PATH` is a worse idea since this behavior is not guaranteed to always work.

**Comment by jondeuce** [comment]
I've never used TestEnv.jl but it looks neat! To be clear: this would still mean reverting to specifying dependencies via [extras] and [targets] and removing `test/Project.toml`, correct? I would just use `TestEnv.activate()` to activate the test environment instead of pushing to `LOAD_PATH`? This seems to be [what is recommended in the discourse post](https://discourse.julialang.org/t/ann-testenv-jl-activate-your-test-enviroment-so-you-can-use-your-test-dependencies/65739).

**Comment by jondeuce** [comment]
Looks like `TestEnv.jl` won't fix the problem. This seems to be hitting a lot of weak points of `Pkg` simultaneously, specifically sub-projects and test environments.

`Pkg` generates `FromFile/Manifest.toml` at test time, but is unable to then merge it with `FromFile/test/Manifest.toml` due to https://github.com/JuliaLang/Pkg.jl/issues/1585. But we somehow need to tell the package manager where to find `FromFileTestPack`.

I think something like `pushfirst!(LOAD_PATH, joinpath(@__DIR__, "FromFileTestPack"))` is not so bad, since it's only the local package that needs to be hacked onto the `LOAD_PATH`. But I've implemented a slightly cleaner solution using `Pkg.develop(path = joinpath(@__DIR__, "FromFileTestPack"))` instead.

**Comment by Roger-luo** [comment]
thanks! great job! Yeah `dev` is more legit for `Pkg` - it is still a pain, however.

**Pull request merged**
