### PR TITLE
Add simple snippet to print out object locations

### PR DESCRIPTION
**Pull request by MilesCranmer**
This will print out which file defines which object. I have found this quite useful for porting my Julia code to use `@from`.

Cheers,
Miles

### CODE REVIEW

**Comment by patrick-kidger** [comment]
(FYI @Roger-luo -- this is something Miles and I were chatting about offline, so this isn't out of the blue.)

Hmm, it doesn't seem to work for me. When I try running it on _top secret project we're collaborating on_ I just get `src/src.jl` printed out to `less`. Any ideas?

**Comment by MilesCranmer** [comment]
Weird, when I run it on that project, I do see everything get printed out.

What shell are you using? Also you wouldn't happen to have neovim aliased to vim, would you?

Can you try this one? It uses `vi` which might not be aliased, and also sets `-u NONE` which turns off any `.vimrc` you might have installed (though IIRC, .vimrc should already be disabled in command-line mode).
```bash
for f in **/*.jl; do echo $f && cat $f | vi - -nes -u NONE -c '%s/#.*//ge' -c '%s/"""\_.\{-}"""//ge' -c '%v/^\S\+/exe "norm dd"' -c '%g/^\(end\>\|@from\>\|using\>\|export\>\|import\>\)/exe "norm dd"' -c '%g/.*/exe "norm >>"' -c ':%p' -c ':q!' | tail -n +2; done
```

**Comment by patrick-kidger** [comment]
Shell is bash. I don't think neovim is around. The above snipppet just prints out `src/src.jl` as well. :/ (I don't really have time to debug this now I'm afraid.)

**Comment by Roger-luo** [comment]
I'm a bit confused on what you want to do here - if you just want to know the file path, why not just find out which module it belongs to and then check out the module path?

**Comment by MilesCranmer** [comment]
@patrick-kidger (once you find time), does the following print all the source code, without the comment lines?
```julia
for f in **/*.jl; do echo $f && cat $f | vi - -nes -u NONE -c '%s/#.*//ge' -c ':%p' -c ':q!' | tail -n +2; done
```
To be honest, if it just prints `src/src.jl`, it sounds like it's crashing in the middle of the loop maybe... Do you have vim installed? 

@Roger-luo. To help explain, here's an example output when I apply this to `SymbolicRegression.jl`:
Screen Shot 2021-02-10 at 3 41 35 PM

This shows me which function is defined where. Then I can go through my code, and add the corresponding
```julia
@from "Utils.jl" import debug_inline
```
wherever I need some object.

For small projects, of course one can usually remember what function is defined in which file. But for larger ones, it's hard. Especially if one just has a bunch of `include(...)` statements, and left it at that. This makes it easier to port large projects to `FromFile.jl`. It was difficult at first to port `SymbolicRegression.jl` to use `@from`, but once I printed out this listing of which function comes from where, it was a lot faster.

Does that make more sense?

**Comment by patrick-kidger** [comment]
Printout:
```
src/src.jl
using FromFile
@from "datasets/datasets.jl" import datasets
@from "models/models.jl" import models
@from "train/train.jl" import train
```

I do have vim installed. (Would be hard to get by without it.)

Maybe try running your snippet on any of a few other machines available to you, see if you can reproduce the behaviour?

**Comment by MilesCranmer** [comment]
Okay, good. It looks like it's actually working! The issue here is just that there are no objects defined in the `src` directory (in our super secret project).

In principle `**/*.jl` should do a recursive glob, but apparently not on macOS. The `**` for recursive searches was introduced in bash v4 (2009), but Mac never updated to v4 because it's GPL licensed (I use `zsh` so didn't notice this). Thus, here's a platform independent snippet, which should work for you, using `find` instead of `**`:
```bash
for f in $(find . -name '*.jl'); do
    echo $f && \
    cat $f | vim - -nes \
        -c '%s/#.*//ge' \
        -c '%s/"""\_.\{-}"""//ge' \
        -c '%v/^\S\+/d_' \
        -c '%g/^\(end\>\|@from\>\|using\>\|export\>\|import\>\)/d_' \
        -c '%g/.*/exe "norm >>"' \
        -c ':%p' -c ':q!' | tail -n +2
done | less
```
I'll put this in the PR.

**Comment by patrick-kidger** [comment]
Haha, I continue to believe that anything on the command line beyond `ls` and `cd` constitutes dark wizardry. (I am completely guilty of instead using Python scripts in the same way you're using vim here.)

Anyway, basically LGTM -- now runs successfully. (And "it runs on my machine" is apparently the bar to entry here.)

**Pull request merged**
