### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by patrick-kidger**
Minor tweaks.

Not adjusting the stuff on `__toplevel__` yet until we've pinned down what we're doing with that.

### CODE REVIEW

**Comment by Roger-luo** [comment]
I tried the new version a bit, without `__imports__` or `__toplevel__` seems much cleaner to me now.

**Comment by patrick-kidger** [comment]
So to be honest I'd still much rather have one of them. I don't like polluting a module's namespace: at least in principle they could clash with something else a user is doing. I don't think this will be viewed a suitable extension for the base language with that as a potential flaw.

Thing is, I couldn't get them to work because of the error about calling `eval` on closed modules. MWE:
```julia
module MyPackage
module A
end
Core.eval(A, :(foo() = "hi"))
end
```
This works in the REPL but breaks when used as a package.

**Comment by Roger-luo** [comment]
Ah right this is because we are mutating the module which makes it not static anymore... I think this is what Stefan was talking about the spooky behavior in root module...

I think in principle we want to give the file module a fullname `PackageName.var"file.jl"` so that we can use the relative path as the identifier for the file module. An ugly workaround might be loading all the files in the root module's `__files__` bare module at once. But this will also require one to declare a macro inside the root module.

But I think this kinda reveals an issue that having this spooky behavior can cause problems to compilation. I guess we may need to create a baremodule that is special treated like `Base.__toplevel__` so that the `from ... import X` always creates the file module statically, which should be possible. But I still want to check this a bit later myself again to see if there is some possible workaround.

> So to be honest I'd still much rather have one of them. I don't like polluting a module's namespace: at least in principle they could clash with something else a user is doing. I don't think this will be viewed a suitable extension for the base language with that as a potential flaw.

I think since it's not a valid variable name in normal code, similar to `#__imports__#`, it's probably fine, but I don't have a strong opinion on the name.

**Comment by patrick-kidger** [comment]
> But I think this kinda reveals an issue that having this spooky behavior can cause problems to compilation. I guess we may need to create a baremodule that is special treated like Base.__toplevel__ so that the from ... import X always creates the file module statically, which should be possible. But I still want to check this a bit later myself again to see if there is some possible workaround.

Yeah, this is my hunch, that we need a bit of extra magic beyond what's normally done. Essentially we'd like to create a module `PackageName.__files__` that is closed at exactly the same time `PackageName` is.

**Pull request merged**
